apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
spec:
  selector:
    matchLabels:
      app: techtrends
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          image: 'maxritter/techtrends:latest'
          ports:
            - containerPort: 3111
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              host: ''
              path: /healthz
              port: 3111
              scheme: HTTP
          readinessProbe:
            httpGet:
              host: ''
              path: /healthz
              port: 3111
              scheme: HTTP
